# Site settings
title: Lorenzo's Music
email: info@lorenzosmusic.com
description: >- # this means to ignore newlines until "baseurl:"
  Experimental art rock band creating open-source music.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lorenzosmusic.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lorenzosmusic
github_username:  lorenzosmusic

# Social Media Configuration
# Uncomment and add your usernames/channel IDs to enable social links
twitter_username: lorenzosmusic
github_username:  lorenzosmusic
# spotify_username: your_spotify_artist_id
youtube_channel: lorenzosmusic
instagram_username: lorenzosmusic
mastodon_username: lorenzosmusic
mastodon_instance: mastodon.social
pixelfed_username: lorenzosmusic
pixelfed_instance: pixelfed.social
bandcamp_username: lorenzosmusic
# soundcloud_username: your_soundcloud_username

# Hero Section Configuration
hero:
  title: "LORENZO'S MUSIC"
  subtitle: "Experimental art rock band creating open-source music"
  background_image: "/assets/images/lorenzos-music-live-shots-header-5.jpg"  # Desktop background image
  background_image_mobile: "/assets/images/lorenzos-music-square-header-band-image.jpg"  # Mobile background image (optional)
  buttons:
    - text: "Listen Now"
      url: "/music"
      style: "primary"
    - text: "About Us"
      url: "/about"
      style: "secondary"
    - text: "Latest Blog"
      url: "/blog"
      style: "outline"

# Music Configuration
music:
  latest_album:
    title: "Lorenzo's Remixes, Volume 2"
    description: "a collection of Lorenzo's Music tracks remixed by us and other artists. It was released on the blocSonic label for Netlabel Day. Our songs get rerouted and reimagined. The album features contributions from: Spiedkiks, Headsnack,Timezone LaFontaine, Velcro Mary, and AxWax. Plus, we also reinterpret and remix six of the songs ourselves "
    image: "/assets/images/album-covers/Lorenzos-Remixes-volume-2-Cover-800px.jpg"
    spotify_url: "https://open.spotify.com/album/4HlXFCbtM3b6Bb8ZTNxnCW?si=LASqoPXTRjaHt2c6ccGwVg"
    bandcamp_url: "https://faircamp.lorenzosmusic.com/lorenzos-remixes-vol-2/"
    tracks:
      - "If I was alone (Da Dun & I Mix)"
      - "Melancholy friction (For Too Long Manifesto Mix)"
      - "Variation witch (Witch Slew Mix)"
      - "Friction called quest (Taim Mix)"
      - "Blue water friction (Boombox Tape Mix)"
      - "Could take for years (Watcha mix)"
      - "I can only miss you (Kikhausen Mix)"
      - "Rainy day friction (Kikhausen Mix)"
      - "If I was alone (AxWax Mix)"
      - "Friction called quest (All that time Velcro Mary Mix)"
      - "Friction called quest (Headsnack Mix)"
      - "Roulette (Break the bank Timezone LaFontaine Mix)"
  
  releases:
    - title: "Friction"
      year: "2025"
      description: "Friction by Lorenzo's Music is a genre-blurring experimental rock album crafted as a movie soundtrack."
      image: "/assets/images/album-covers/friction-album-cover-art-lorenzos-music-600px.png"
      spotify_url: "https://distrokid.com/hyperfollow/lorenzosmusic/friction"
      bandcamp_url: "https://faircamp.lorenzosmusic.com/friction/"
    - title: "If I was alone EP"
      year: "2024"
      description: "A collection of experimental/Lo-Fi Rock tracks that were released from 2022-2024."
      image: "/assets/images/album-covers/lorenzos-if-i-was-alone-artwork-no-shadow.png"
      spotify_url: "https://distrokid.com/hyperfollow/lorenzosmusic/if-i-was-alone"
      bandcamp_url: "https://faircamp.lorenzosmusic.com/if-i-was-alone-ep/"
    - title: "Lorenzo's Remixes, Volume 1"
      year: "2024"
      description: "An album of Lorenzo's Music tracks remixed by other artists on the blocSonic Netlabel."
      image: "/assets/images/album-covers/lorenzos-music-lorenzos-remixes-vol-1-00-BSMX0230-Cover-Full.jpg"
      spotify_url: "https://distrokid.com/hyperfollow/lorenzosmusic/lorenzos-remixes-volume-1"
      bandcamp_url: "https://faircamp.lorenzosmusic.com/lorenzos-remixes-vol-1/"
    - title: "Spaghetti Mid-Western"
      year: "2020"
      description: "A collage of audio from studio sessionsn & live streamed practices that were spliced, edited and arranged to create these songs."
      image: "/assets/images/album-covers/spaghetti-mid-western-cover.png"
      spotify_url: "https://sl.onerpm.com/6571103960"
      bandcamp_url: "https://faircamp.lorenzosmusic.com/spaghetti-mid-western/"
    - title: "Rom-Comm Mixtape"
      year: "2018"
      description: "An experimental artistic venture. A collection of songs and sounds that are a personal expression of life and tribulation."
      image: "/assets/images/album-covers/lorenzos-music-rom-comm-mixtape.jpg"
      spotify_url: "https://onerpm.link/3522871603"
      bandcamp_url: "https://faircamp.lorenzosmusic.com/rom-comm-mixtape/"



# Build settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Lorenzo"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 

# Pagination settings for blog
paginate: 9
paginate_path: "/blog/page:num/"
